accounts/urls.py
from django.conf.urls import url
from .views import view_account, register, login


urlpatterns = [
   url(r'^/', view_account,  name='view_account'),
   url(r'^register/', register,  name='register'),
   url(r'^login/', login,  name='login'),
   
]

aeon_pc_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home import urls as urls_home
from parts import urls as part_urls
from pc_builder import urls as builder_urls
from accounts import urls as accounts_urls
from .settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls, name=''),
    url(r'^', include(urls_home, namespace='home'), name='home'),
    url(r'^parts/', include(part_urls, namespace='part'), name='part'),
    url(r'^accounts/', include(accounts_urls, namespace='accounts'), name='accounts'),
    url(r'^builder/', include(builder_urls, namespace='builder'), name='builder'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

home/urls.py
from django.conf.urls import url
from .views import home, about
from accounts.views import logout

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^about/$', about, name='about'),
]

parts/urls.py
from django.conf.urls import url
from .views import show_parts

urlpatterns = [
    url(r'^$', show_parts, name='show_parts'),
]

pc_builder/urls.py
from django.conf.urls import url
from .views import start_builder, select_parts, compare_item, configurations


urlpatterns = [
    url(r'^start/$', start_builder, name='start_builder'),
    url(r'^parts/$', select_parts, name='select_parts'),
    url(r'^compare/$', compare_item, name='compare_item'),
    url(r'^configurations/$', configurations, name='configurations'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

checkout/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

crawler/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

parts/models.py
from django.db import models
from separatedvaluesfield.models import SeparatedValuesField
        
class part(models.Model):
    name = models.CharField(max_length=254, default='')
    url = models.CharField(max_length=254, default='')
    category = models.CharField(max_length=254, default='')
    image = models.ImageField(upload_to='media/images', max_length=None)
    description = models.TextField()
    price = models.DecimalField(max_digits=9, decimal_places=2, null=True)
    rating = models.IntegerField(blank=False, default = 1)
    specs_categorys = SeparatedValuesField(max_length=512, token=',' , null=True)
    specs_values = SeparatedValuesField(max_length=512, token=',', null=True)
    available_amount = models.CharField(max_length=15, default='')
    available_from = models.DateField(blank=True, null=True)
    countsold= models.IntegerField(blank=False, default = 1)
    
    def __str__(self):
        return self.name

pc_builder/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms

class LoginForm(forms.Form):
    """
    Used by the user to enter login credentials
    """
    user_email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib import messages, auth

# Create your views here.

def view_account(request):

    """A view that displays the index page"""
    return render(request, "view_accounts.html")
    
    
def logout(request):
    auth.logout(request)
    messages.success(request, 'You have successfully logged out!')
    return render(request, "home/index.html")
    
def register(request):
    
    return render(request, "register.html")
    
def login(request):
    
    return render(request, "login.html")

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

checkout/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def home(request):

    """A view that displays the index page"""
    return render(request, "home/index.html")
    
def about(request):

    """A view that displays the index page"""
    return render(request, "home/about.html")
    

    

parts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
def show_parts(request):

    """A view that displays the index page"""
    return render(request, "products.html")

pc_builder/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from parts.models import part
import operator

# Create your views here.

def start_builder(request):

    """A view that displays the index page"""
    return render(request, "builder.html")


def select_parts(request):
    all_products=part.objects.filter(category="Gehäuse")
    par=[]
    for i,prod in enumerate(all_products):
        par.append(part.objects.filter(product=prod.id))
    print(par)
    return render(request, "parts.html")
    #{'products': pages}
def compare_item(request):

    return render(request, "compare.html")
    
    
def configurations(request):

    """A view that displays the index page"""
    return render(request, "configurations.html")

accounts/templates/login.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %}
<div class="gtco-services gtco-section">
    <div class="gtco-container">
        <form class="form-horizontal" action="{% url 'accounts:login' %}">
            <div class="form-group">
                <label class="control-label col-sm-2" for="email">Username or Email:</label>
                <div class="col-sm-10">
                    <input type="user_email" class="form-control" id="user_email" placeholder="Enter credentials" name="user_email">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2" for="pwd">Password:</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <div class="checkbox">
                        <label><input type="checkbox" name="remember"> Remember me</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

accounts/templates/register.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %}
    <div class="container">
        <div class="row">
            <p>Will be the register page.</p>
            </div>
    </div>
{% endblock %}

accounts/templates/view_accounts.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %}
    <div class="container">
        <div class="row">
            <p> Will be the accounts site.</p>
            </div>
    </div>
{% endblock %}

home/templates/home/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<!--
	Cube by FreeHTML5.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://freehtml5.co
-->
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>AEON CUSTOM PC's</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="FreeHTML5.co" />

	<!-- Facebook and Twitter integration -->

	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link rel="shortcut icon" href="{% static 'images/icon.ico' %}" type="image/x-icon" sizes="16x16 24x24 32x32 64x64" />
	<link href="{% static 'fonts/railway_regular_macroman/stylesheet.css' %}" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static  'css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static  'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

</head>

<body>

	<div class="gtco-loader"></div>

	<div id="page">

		<nav class="gtco-nav" role="navigation">
			<div class="gtco-container">

				<div class="row">
					<div class="col-sm-2 col-xs-12">
						<div id="gtco-logo"><a href="{% url 'home:home' %}"><img src="{% static 'images/logo.ico' %}" alt="Aeon custom PC"></a></div>
					</div>
					<div class="col-xs-10 text-right menu-1">
						<ul>
							<li class="active"><a href="{% url 'home:home' %}">Home</a></li>
							<li><a href="{% url 'home:about' %}">About</a></li>
							<li class="has-dropdown">
								<a href="services.html">Services</a>
								<ul class="dropdown">
									<li><a href="#">Web Design</a></li>
									<li><a href="#">eCommerce</a></li>
									<li><a href="#">Branding</a></li>
									<li><a href="#">API</a></li>
								</ul>
							</li>
							<li class="has-dropdown">
								<a href="#">Dropdown</a>
								<ul class="dropdown">
									<li><a href="#">HTML5</a></li>
									<li><a href="#">CSS3</a></li>
									<li><a href="#">Sass</a></li>
									<li><a href="#">jQuery</a></li>
								</ul>
							</li>
							{% if not user.is_authenticated %}
							<li><a href="{% url 'accounts:register' %}">Register</a></li>
							<li><a href="{% url 'accounts:login' %}">Login</a></li>
							{% endif %}
							
							{% if user.is_authenticated %}
							<li><a href="{% url 'home:logout' %}">Logout</a></li>
							{% endif %}
						</ul>
					</div>
				</div>

			</div>
		</nav>
		
		<div class="gtco-container">
		{% block content %}
		{% endblock %}
		</div>

		<footer id="gtco-footer" class="gtco-section" role="contentinfo">
			<div class="gtco-container">
				<div class="row row-pb-md">
					<div class="col-md-8 col-md-offset-2 gtco-cta text-center">
						<h3>We Love To Talk About Your Business</h3>
						<p><a href="#" class="btn btn-white btn-outline">Contact Us</a></p>
					</div>
				</div>
				<div class="row row-pb-md">
					<div class="col-md-4 gtco-widget gtco-footer-paragraph">
						<h3>Cube</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod.</p>
					</div>
					<div class="col-md-4 gtco-footer-link">
						<div class="row">
							<div class="col-md-6">
								<ul class="gtco-list-link">
									<li><a href="#">Home</a></li>
									<li><a href="#">Features</a></li>
									<li><a href="#">Products</a></li>
									<li><a href="#">Testimonial</a></li>
									<li><a href="#">Contact</a></li>
								</ul>
							</div>
							<div class="col-md-6">
								<p>
									<a href="tel://1234567890">+1 234 4565 2342</a> <br>
									<a href="#">info@domain.com</a>
								</p>
							</div>
						</div>
					</div>
					<div class="col-md-4 gtco-footer-subscribe">
						<form class="form-inline">
							<div class="form-group">
								<label class="sr-only" for="exampleInputEmail3">Email address</label>
								<input type="email" class="form-control" id="" placeholder="Email">
							</div>
							<button type="submit" class="btn btn-primary">Send</button>
						</form>
					</div>
				</div>
			</div>
			<div class="gtco-copyright">
				<div class="gtco-container">
					<div class="row">
						<div class="col-md-6 text-left">
							<p><small>&copy; 2016 Free HTML5. All Rights Reserved. </small></p>
						</div>
						<div class="col-md-6 text-right">
							<p><small>Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://pixeden.com/" target="_blank">Pixeden</a> &amp; <a href="http://unsplash.com" target="_blank">Unsplash</a></small> </p>
						</div>
					</div>
				</div>
			</div>
		</footer>

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>

	<!-- jQuery -->
	<script src=" {% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}

<header id="gtco-header" class="gtco-cover" role="banner">
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">
                <div class="display-t">
                    <div class="display-tc">
                        <div class="row">
                            <div class="col-md-5 text-center header-img animate-box">
                                <img src="{% static 'images/case.jpg' %}" alt="Free HTML5 Website Template by FreeHTML5.co">
                            </div>
                            <div class="col-md-7 copy animate-box">
                                <h1>Bored of having a standard PC? Try out the PC-builder and create your custom PC today.</h1>
                                <p>AEON PC-builder is a program which lets your search and compare hundrets of parts. And chose the one which is right for you.</p>
                                <p><a href="{% url 'builder:start_builder' %}" target="_self" class="btn btn-white">Build your custom PC system now!</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END #gtco-header -->

<div class="gtco-services gtco-section">
    <div class="gtco-container">
        <div class="row row-pb-sm">
            <div class="col-md-8 col-md-offset-2 gtco-heading text-center">
                <h2>Make your life simpler.</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.</p>
                <p><a href="https://vimeo.com/channels/staffpicks/93951774" class="btn btn-special popup-vimeo">Watch The Video</a></p>
            </div>
        </div>
        <div class="row row-pb-md">
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service">
                    <h3><i class="ti-pie-chart"></i> Chose parts</h3>
                    <p>Chose the hardware you want to use in your system. We currently offer 20.000 diffrent parts.
                    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service">
                    <h3><i class="ti-ruler-pencil"></i> Compare</h3>
                    <p>Compare the hardware as you can select multiple parts and see what fits you best.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service">
                    <h3><i class="ti-settings"></i> Order</h3>
                    <p>After you created your dream setup just press the order button and we will build it for you.</p>
                </div>
            </div>

            <div class="clearfix visible-md-block visible-sm-block"></div>

        </div>
    </div>
</div>
<!-- END .gtco-services -->

<div class="gtco-section gtco-products">
    <div class="gtco-container">
        <div class="row row-pb-sm">
            <div class="col-md-8 col-md-offset-2 gtco-heading text-center">
                <h2>The currently most ordered systems:</h2>
                <p>Somebody else already created your perfect PC? Don't bother to create it again. Search from hundrets of the most popular systems on our site.</p>
            </div>
        </div>
        <div class="row row-pb-md">
            <div class="col-md-4 col-sm-4">
                <a href="#" class="gtco-item two-row bg-img animate-box" style="background-image: url({% static 'images/img_1.jpg' %})">
                    <div class="overlay">
                        <i class="ti-arrow-top-right"></i>
                        <div class="copy">
                            <h3>Paper Hot Cup</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/img_1.jpg' %}" class="hidden" alt="Free HTML5 Website Template by FreeHTML5.co">
                </a>
                <a href="#" class="gtco-item two-row bg-img animate-box" style="background-image: url({% static 'images/img_2.jpg' %})">
                    <div class="overlay">
                        <i class="ti-arrow-top-right"></i>
                        <div class="copy">
                            <h3>Notepad Mockup</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/img_2.jpg' %}" class="hidden" alt="Free HTML5 Website Template by FreeHTML5.co">
                </a>
            </div>
            <div class="col-md-4 col-sm-4">
                <a href="#" class="gtco-item one-row bg-img animate-box" style="background-image: url({% static 'images/img_md_1.jpg' %})">
                    <div class="overlay">
                        <i class="ti-arrow-top-right"></i>
                        <div class="copy">
                            <h3>Paper Pouch</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/img_md_1.jpg' %}" class="hidden" alt="Free HTML5 Website Template by FreeHTML5.co">
                </a>
            </div>
            <div class="col-md-4 col-sm-4">
                <a href="#" class="gtco-item two-row bg-img animate-box" style="background-image: url({% static 'images/img_3.jpg' %})">
                    <div class="overlay">
                        <i class="ti-arrow-top-right"></i>
                        <div class="copy">
                            <h3>Fancy 3D</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/img_3.jpg' %}" class="hidden" alt="Free HTML5 Website Template by FreeHTML5.co">
                </a>
                <a href="#" class="gtco-item two-row bg-img animate-box" style="background-image: url({% static 'images/img_4.jpg' %})">
                    <div class="overlay">
                        <i class="ti-arrow-top-right"></i>
                        <div class="copy">
                            <h3>Hard Cover Book</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <img src="{% static 'images/person_1.jpg' %}" class="hidden" alt="Free HTML5 Website Template by FreeHTML5.co">
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p><a href="{% url 'builder:configurations' %}" target="_blank" class="btn btn-special">Browser popular configurations</a></p>
            </div>
        </div>
    </div>
</div>
<!-- END .gtco-products -->


{% endblock %}

parts/templates/products.html
{% extends 'home/base.html' %} {% block content %}
<div class="items_wrapper">
    <div class="items1">DIV1</div>
    <div class="items1">DIV2</div>
    <div class="items1">DIV3</div>
    <div class="items1">DIV4</div>
    <div class="items1">DIV5</div>
</div>
{% endblock %}

pc_builder/templates/builder.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="gtco-services gtco-section">
    <div class="gtco-container">
        <div class="row row-pb-sm">
            <div class="col-md-8 col-md-offset-2 gtco-heading text-center">
                <h2>Make your life simpler.</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus placerat enim et urna sagittis, rhoncus euismod erat tincidunt. Donec tincidunt volutpat erat.</p>
                <p><a target="_self" href="{% url 'builder:select_parts' %}">Get started!</a></p>
            </div>
        </div>
        <div class="row row-pb-md">
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service">
                    <h3><i class="ti-pie-chart"></i> Marketing</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur voluptatibus nesciunt, est alias deleniti ipsum fuga ullam maxime repudiandae neque, ad. Maiores quis atque, culpa rem inventore vero amet praesentium, quam sint,
                        magnam reprehenderit doloremque.
                    </p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service animate-change">
                    <h3><i class="ti-ruler-pencil"></i> Design</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima quidem quae, assumenda dolores ad pariatur! Deleniti debitis, voluptatem! Omnis enim magnam perspiciatis, natus. Ipsum distinctio, voluptatibus vero laboriosam sequi!
                        Officia fuga quam eveniet quo similique!</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-4 service-wrap">
                <div class="service">
                    <h3><i class="ti-settings"></i> Development</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta aperiam, maiores officia alias accusantium fugiat, doloremque voluptas, voluptatem dolore vel animi praesentium saepe unde consequuntur, eum asperiores odit aliquam error
                        nulla impedit repellendus. Nesciunt, delectus.</p>
                </div>
            </div>

            <div class="clearfix visible-md-block visible-sm-block"></div>

        </div>
    </div>
</div>

{% endblock %}

pc_builder/templates/configurations.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %}
<div class="gtco-section gtco-products">
    <div class="gtco-container">
        {% for product in products %}

        <div class="col-sm-6 col-md-4 card" style="height: 550px;">
            <div class="thumbnail" style="height: 530px;">
                <img height='400' width='400' src="{{MEDIA_URL}}{{product.image}}" alt="">

                <h4 class="pull-right">€{{product.price}}</h4>
                <h4><a href="{% url 'builder:compare_item' %}">{{product.product}}</a>
                </h4>
            </div>
            <div class="ratings">
                <p class="pull-right"></p>
                <p>
                    <span class="text-warning"></span>
                </p>
            </div>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

pc_builder/templates/parts.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %}
<div class="gtco-section gtco-products">
    <div class="gtco-container">
        {% for product in products %}

        <div class="col-sm-6 col-md-4 card" style="height: 550px;">
            <div class="thumbnail" style="height: 530px;">
                <img height='400' width='400' src="{{MEDIA_URL}}{{product.image}}" alt="">

                <h4 class="pull-right">€{{product.price}}</h4>
                <h4><a href="{% url 'builder:compare_item' %}">{{product.product}}</a>
                </h4>
            </div>
            <div class="ratings">
                <p class="pull-right"></p>
                <p>
                    <span class="text-warning"></span>
                </p>
            </div>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}